package:
  name: python-2.7
  version: 2.7.18.10-git
  epoch: 0
  description: "The Python programming language"
  copyright:
    - license: PSF-2.0
  resources:
    cpu: 8
    memory: 8Gi
  dependencies:
    provides:
      - python2=${{package.full-version}}
      - python-2=${{package.full-version}}
    runtime:
      - ${{package.name}}-base=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - bzip2-dev
      - ca-certificates-bundle
      - expat-dev
      - gdbm-dev
      - libffi-dev
      - linux-headers
      - mpdecimal-dev
      - ncurses-dev
      - openssl-dev
      - readline-dev
      - sqlite-dev
      - xz-dev
      - zlib-dev

# creates helpful python2.M and 2.M variables
var-transforms:
  - from: ${{package.name}}
    match: '-'
    replace: ''
    to: python
  - from: ${{package.version}}
    match: (\d).(\d+).(\d+)
    replace: '$1.$2'
    to: pyversion

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 9f7bbf95c14a9b8fe92ea9ebe40e674a630673ab
      repository: https://github.com/ActiveState/cpython
      branch: 2.7

  - uses: patch
    with:
      patches: openssl3-compatibility.diff

  - uses: patch
    with:
      patches: openssl3-data.diff

  - uses: patch
    with:
      patches: openssl3-unexpected-eof.diff

  - uses: patch
    with:
      patches: openssl3-load-verify-error.diff

  - uses: patch
    with:
      patches: openssl3-version.diff

  - uses: patch
    with:
      patches: openssl3-tests-tlsv1.diff

  - uses: patch
    with:
      patches: openssl3-fix-detection.diff

  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --build=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --enable-ipv6 \
         --enable-shared \
         --without-lto \
         --with-computed-gotos \
         --with-dbmliborder=gdbm:ndbm \
         --with-system-expat \
         --with-system-ffi \
         --with-lto

      rm Lib/test/test_ftplib.py

      export EXTRATESTOPTS=--list-tests

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      find ${{targets.destdir}}/usr/lib -type f -name 'libpython*.a' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'test' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'tests' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'idle_test' -exec rm -rf '{}' +

      cd ${{targets.destdir}}/usr/bin
      rm -f idle3* 2to3*

      # Drop site-packages README.txt to avoid SCA dep on python2~3.M
      cd ${{targets.destdir}}/usr/lib/${{vars.python}}

  - runs: |
      find ${{targets.destdir}}/usr/lib -type f -name '*.pyc' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type f -name '*.pyo' -exec rm -rf '{}' +

      export LD_LIBRARY_PATH="${{targets.destdir}}/usr/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
      # ${{targets.destdir}}/usr/bin/${{vars.python}} -m compileall --invalidation-mode=unchecked-hash -r100 ${{targets.destdir}}/usr/lib/

  - uses: strip

subpackages:
  - name: "${{package.name}}-base"
    description: "${{package.name}} as /usr/bin/python3"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin ${{targets.subpkgdir}}/usr/lib
          mv -v ${{targets.destdir}}/usr/lib/${{vars.python}} \
             ${{targets.subpkgdir}}/usr/lib
          mv -v ${{targets.destdir}}/usr/lib/libpython*.so.* \
             ${{targets.subpkgdir}}/usr/lib

update:
  enabled: true
  shared: true
  github:
    identifier: python/cpython
    strip-prefix: v
    tag-filter: v2.7
    use-tag: true
